version: '3'

volumes:
  postgres_volume:

services:
  auth:
    image: cr.selcloud.ru/noskov-sergey/auth-server:latest
    env_file:
      - .env
    ports:
      - "${GRPC_PORT}:${GRPC_PORT}"
    depends_on:
      - db
    restart: on-failure

  db:
    image: postgres:14-alpine3.20
    env_file:
      - .env
    ports:
      - "54321:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  migrator:
    build:
      context: .
      dockerfile: migration.Dockerfile
    restart: on-failure
    env_file:
      - .env